const fs = require('fs');
const path = require('path');

// Read the CSV file
const csvPath = path.join(__dirname, '../data/common_words.csv');
const csvContent = fs.readFileSync(csvPath, 'utf-8');
const lines = csvContent.trim().split('\n');

// Emoji mapping based on English words
const emojiMap = {
  'hello': '👋',
  'hi': '👋',
  'thank you': '🙏',
  'thanks': '🙏',
  'sorry': '😔',
  'yes': '✅',
  'no': '❌',
  'water': '💧',
  'apple': '🍎',
  'house': '🏠',
  'school': '🏫',
  'friend': '👫',
  'love': '❤️',
  'to like': '👍',
  'to eat': '🍽️',
  'to see': '👀',
  'to go': '🚶',
  'to come': '👋',
  'to do': '⚙️',
  'to exist': '✨',
  'to not exist': '❌',
  'good': '👍',
  'bad': '👎',
  'big': '🔵',
  'small': '🔴',
  'many': '📦',
  'few': '📉',
  'new': '🆕',
  'old': '🕰️',
  'pretty': '💅',
  'beautiful': '✨',
  'happy': '😊',
  'sad': '😢',
  'difficult': '😓',
  'easy': '😎',
  'fast': '⚡',
  'slow': '🐌',
  'warm': '☀️',
  'cold': '❄️',
  'hot': '🔥',
  'cool': '❄️',
  'delicious': '😋',
  'not delicious': '😕',
  'hungry': '🍽️',
  'thirsty': '💧',
  'tired': '😴',
  'sleepy': '😴',
  'glad': '😄',
  'angry': '😠',
  'scary': '😱',
  'fun': '🎉',
  'boring': '😑',
  'important': '⭐',
  'necessary': '📌',
  'possible': '✅',
  'impossible': '❌',
  'correct': '✅',
  'wrong': '❌',
  'same': '🔄',
  'different': '🔀',
  'similar': '🔁',
  'close': '📍',
  'far': '🗺️',
  'high': '⬆️',
  'low': '⬇️',
  'long': '📏',
  'short': '📐',
  'wide': '↔️',
  'narrow': '↕️',
  'deep': '⬇️',
  'shallow': '💧',
  'heavy': '⚖️',
  'light': '💡',
  'hard': '💎',
  'soft': '🪶',
  'bright': '☀️',
  'dark': '🌙',
  'quiet': '🤫',
  'noisy': '🔊',
  'clean': '✨',
  'dirty': '💩',
  'healthy': '💪',
  'sick': '🤒',
  'rich': '💰',
  'poor': '💸',
  'smart': '🧠',
  'stupid': '🤪',
  'kind': '🤗',
  'rude': '😤',
  'brave': '🦁',
  'honest': '🤝',
  'forgive': '🙏',
  'help': '🆘',
  'apologize': '🙇',
  'thankful': '🙏',
  'congratulate': '🎉',
  'meet': '🤝',
  'make': '🔨',
  'use': '🔧',
  'want': '👆',
  'dislike': '👎',
  'love': '❤️',
  'hate': '💔',
  'think': '🤔',
  'know': '🧠',
  'not know': '❓',
  'remember': '🧠',
  'forget': '🧹',
  'learn': '📚',
  'teach': '👨‍🏫',
  'read': '📖',
  'write': '✍️',
  'listen': '👂',
  'speak': '🗣️',
  'talk': '💬',
  'ask': '❓',
  'answer': '💬',
  'tell': '📢',
  'explain': '📝',
  'understand': '💡',
  'start': '🚀',
  'finish': '🏁',
  'continue': '▶️',
  'stop': '⏹️',
  'wait': '⏳',
  'hurry': '🏃',
  'late': '⏰',
  'early': '🌅',
  'quickly': '⚡',
  'slowly': '🐌',
  'often': '🔄',
  'sometimes': '⏰',
  'always': '♾️',
  'never': '🚫',
  'today': '📅',
  'yesterday': '📆',
  'tomorrow': '📅',
  'now': '⏰',
  'later': '⏳',
  'before': '⬅️',
  'after': '➡️',
  'morning': '🌅',
  'lunch': '🍽️',
  'evening': '🌆',
  'night': '🌙',
  'time': '⏰',
  'date': '📅',
  'day of week': '📆',
  'month': '📅',
  'year': '📆',
  'hour': '🕐',
  'minute': '⏱️',
  'second': '⏱️',
  'Monday': '📅',
  'Tuesday': '📅',
  'Wednesday': '📅',
  'Thursday': '📅',
  'Friday': '📅',
  'Saturday': '📅',
  'Sunday': '📅',
  'January': '❄️',
  'February': '💝',
  'March': '🌸',
  'April': '🌷',
  'May': '🌺',
  'June': '☀️',
  'July': '🌞',
  'August': '🌻',
  'September': '🍂',
  'October': '🎃',
  'November': '🍁',
  'December': '🎄',
  'person': '👤',
  'man': '👨',
  'woman': '👩',
  'child': '👶',
  'baby': '👶',
  'student': '🎓',
  'teacher': '👨‍🏫',
  'doctor': '👨‍⚕️',
  'nurse': '👩‍⚕️',
  'mom': '👩',
  'dad': '👨',
  'older brother': '👨',
  'older sister': '👩',
  'younger sibling': '👶',
  'younger brother': '👦',
  'younger sister': '👧',
  'grandfather': '👴',
  'grandmother': '👵',
  'cat': '🐱',
  'dog': '🐕',
  'bird': '🐦',
  'fish': '🐟',
  'tree': '🌳',
  'flower': '🌸',
  'grass': '🌱',
  'sky': '☁️',
  'cloud': '☁️',
  'sun': '☀️',
  'moon': '🌙',
  'star': '⭐',
  'rain': '🌧️',
  'snow': '❄️',
  'wind': '💨',
  'lightning': '⚡',
  'thunder': '⛈️',
  'weather': '🌤️',
  'clear': '☀️',
  'cloudy': '☁️',
  'spring': '🌸',
  'summer': '☀️',
  'autumn': '🍂',
  'winter': '❄️',
  'food': '🍽️',
  'rice': '🍚',
  'soup': '🍲',
  'meat': '🥩',
  'vegetable': '🥬',
  'fruit': '🍎',
  'bread': '🍞',
  'milk': '🥛',
  'tea': '🍵',
  'coffee': '☕',
  'juice': '🧃',
  'beer': '🍺',
  'soju': '🍶',
  'kimchi': '🥬',
  'bulgogi': '🥩',
  'bibimbap': '🍲',
  'kimbap': '🍱',
  'ramen': '🍜',
  'tteokbokki': '🍢',
  'chicken': '🍗',
  'pizza': '🍕',
  'hamburger': '🍔',
  'snack': '🍪',
  'candy': '🍬',
  'chocolate': '🍫',
  'ice cream': '🍦',
  'cake': '🎂',
  'banana': '🍌',
  'orange': '🍊',
  'grape': '🍇',
  'strawberry': '🍓',
  'watermelon': '🍉',
  'peach': '🍑',
  'pear': '🍐',
  'cherry': '🍒',
  'kiwi': '🥝',
  'pineapple': '🍍',
  'mango': '🥭',
  'lemon': '🍋',
  'carrot': '🥕',
  'onion': '🧅',
  'garlic': '🧄',
  'potato': '🥔',
  'sweet potato': '🍠',
  'tomato': '🍅',
  'cucumber': '🥒',
  'lettuce': '🥬',
  'cabbage': '🥬',
  'broccoli': '🥦',
  'mushroom': '🍄',
  'pepper': '🌶️',
  'clothes': '👕',
  'shirt': '👔',
  'pants': '👖',
  'skirt': '👗',
  'dress': '👗',
  'jacket': '🧥',
  'coat': '🧥',
  'hat': '🎩',
  'shoes': '👟',
  'boots': '👢',
  'socks': '🧦',
  'gloves': '🧤',
  'scarf': '🧣',
  'bag': '👜',
  'wallet': '👛',
  'watch': '⌚',
  'glasses': '👓',
  'earrings': '👂',
  'necklace': '📿',
  'ring': '💍',
  'room': '🚪',
  'bedroom': '🛏️',
  'living room': '🛋️',
  'kitchen': '🍳',
  'bathroom': '🚿',
  'bathtub': '🛁',
  'shower': '🚿',
  'bed': '🛏️',
  'blanket': '🛏️',
  'pillow': '🛏️',
  'chair': '🪑',
  'table': '🪑',
  'sofa': '🛋️',
  'desk': '🪑',
  'bookshelf': '📚',
  'refrigerator': '❄️',
  'microwave': '📡',
  'washing machine': '🌀',
  'vacuum cleaner': '🧹',
  'television': '📺',
  'computer': '💻',
  'laptop': '💻',
  'smartphone': '📱',
  'tablet': '📱',
  'internet': '🌐',
  'email': '📧',
  'message': '💬',
  'phone': '📞',
  'call': '📞',
  'text message': '💬',
  'camera': '📷',
  'photo': '📸',
  'movie': '🎬',
  'music': '🎵',
  'song': '🎵',
  'book': '📚',
  'newspaper': '📰',
  'magazine': '📖',
  'pen': '✏️',
  'pencil': '✏️',
  'paper': '📄',
  'scissors': '✂️',
  'glue': '🧴',
  'ruler': '📏',
  'eraser': '🧹',
  'notebook': '📓',
  'university': '🏫',
  'classroom': '🏫',
  'library': '📚',
  'playground': '🛝',
  'professor': '👨‍🏫',
  'class': '📚',
  'subject': '📖',
  'homework': '📝',
  'exam': '📝',
  'grade': '📊',
  'study': '📚',
  'draw': '🎨',
  'color': '🎨',
  'red': '🔴',
  'orange': '🟠',
  'yellow': '🟡',
  'green': '🟢',
  'blue': '🔵',
  'purple': '🟣',
  'pink': '🩷',
  'black': '⚫',
  'white': '⚪',
  'gray': '⚪',
  'brown': '🟤',
  'number': '🔢',
  'zero': '0️⃣',
  'one': '1️⃣',
  'two': '2️⃣',
  'three': '3️⃣',
  'four': '4️⃣',
  'five': '5️⃣',
  'six': '6️⃣',
  'seven': '7️⃣',
  'eight': '8️⃣',
  'nine': '9️⃣',
  'ten': '🔟',
  'eleven': '1️⃣1️⃣',
  'twelve': '1️⃣2️⃣',
  'twenty': '2️⃣0️⃣',
  'thirty': '3️⃣0️⃣',
  'forty': '4️⃣0️⃣',
  'fifty': '5️⃣0️⃣',
  'sixty': '6️⃣0️⃣',
  'seventy': '7️⃣0️⃣',
  'eighty': '8️⃣0️⃣',
  'ninety': '9️⃣0️⃣',
  'hundred': '💯',
  'thousand': '1️⃣0️⃣0️⃣0️⃣',
  'ten thousand': '1️⃣0️⃣0️⃣0️⃣0️⃣',
  'million': '💵',
  'billion': '💰',
  'first': '1️⃣',
  'second': '2️⃣',
  'third': '3️⃣',
  'fourth': '4️⃣',
  'fifth': '5️⃣',
  'how many': '❓',
  'how much': '💰',
  'where': '📍',
  'when': '⏰',
  'who': '👤',
  'what': '❓',
  'how': '❓',
  'why': '❓',
  'which': '❓',
  'what kind': '❓',
  'what time': '🕐',
  'this': '👉',
  'that': '👉',
  'here': '📍',
  'there': '📍',
  'over there': '📍',
  'this way': '👉',
  'that way': '👉',
  'day after tomorrow': '📅',
  'day before yesterday': '📅',
  'this week': '📅',
  'last week': '📅',
  'next week': '📅',
  'this month': '📅',
  'last month': '📅',
  'next month': '📅',
  'this year': '📅',
  'last year': '📅',
  'next year': '📅',
  'these days': '📅',
  'recently': '🕐',
  'in the past': '⬅️',
  'soon': '⏳',
  'right away': '⚡',
  'immediately': '⚡',
  'earlier': '⏰',
  'occasionally': '⏰',
  'almost': '📊',
  'not at all': '❌',
  'already': '✅',
  'yet': '⏳',
  'hurry': '🏃',
  'leisurely': '🚶',
  'quietly': '🤫',
  'noisily': '🔊',
  'loudly': '🔊',
  'highly': '⬆️',
  'lowly': '⬇️',
  'deeply': '⬇️',
  'shallowly': '💧',
  'widely': '↔️',
  'narrowly': '↕️',
  'longly': '📏',
  'shortly': '📐',
  'heavily': '⚖️',
  'lightly': '💡',
  'hardly': '💎',
  'softly': '🪶',
  'hotly': '🔥',
  'coldly': '❄️',
  'warmly': '☀️',
  'coolly': '❄️',
  'brightly': '☀️',
  'darkly': '🌙',
  'cleanly': '✨',
  'dirtily': '💩',
  'healthily': '💪',
  'sickly': '🤒',
  'smartly': '🧠',
  'stupidly': '🤪',
  'kindly': '🤗',
  'rudely': '😤',
  'bravely': '🦁',
  'cowardly': '😰',
  'honestly': '🤝',
  'lyingly': '🤥',
  'forgivingly': '🙏',
  'helpfully': '🆘',
  'apologetically': '🙇',
  'thankfully': '🙏',
  'congratulatorily': '🎉',
  'meeting': '🤝',
  'making': '🔨',
  'using': '🔧',
  'needing': '📌',
  'wanting': '👆',
  'liking': '👍',
  'disliking': '👎',
  'loving': '❤️',
  'hating': '💔',
  'thinking': '🤔',
  'knowing': '🧠',
  'not knowing': '❓',
  'remembering': '🧠',
  'forgetting': '🧹',
  'learning': '📚',
  'teaching': '👨‍🏫',
  'reading': '📖',
  'writing': '✍️',
  'listening': '👂',
  'speaking': '🗣️',
  'talking': '💬',
  'asking': '❓',
  'answering': '💬',
  'telling': '📢',
  'explaining': '📝',
  'understanding': '💡',
  'not understanding': '❓',
  'starting': '🚀',
  'finishing': '🏁',
  'continuing': '▶️',
  'stopping': '⏹️',
  'waiting': '⏳',
  'hurrying': '🏃',
  'being late': '⏰',
};

function getEmoji(english) {
  // Normalize the English text
  const normalized = english.toLowerCase().trim();
  
  // Direct match
  if (emojiMap[normalized]) {
    return emojiMap[normalized];
  }
  
  // Try partial matches for compound words
  for (const [key, emoji] of Object.entries(emojiMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return emoji;
    }
  }
  
  // Return empty if no match
  return '';
}

// Process the CSV
const header = lines[0];
const newHeader = header + ',emoji,imageUrl';
const newLines = [newHeader];

for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  const [korean, english] = line.split(',');
  const emoji = getEmoji(english);
  const imageUrl = ''; // Leave blank as requested
  newLines.push(`${korean},${english},${emoji},${imageUrl}`);
}

// Write the updated CSV
const newCsvContent = newLines.join('\n');
fs.writeFileSync(csvPath, newCsvContent, 'utf-8');

console.log(`Updated CSV with emoji and imageUrl columns. Processed ${lines.length - 1} words.`);

